name: Sonar
on: [push]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Docker Compose
        run: docker-compose --env-file=env/.env.local up -d

      - name: Update Packages
        run:
          sudo apt-get update

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          POSTGRES_URL: jdbc:postgresql://localhost:5400/banking_kata_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_PASSWORD: b4EA2xC6LlKnlizPu9bwRRrQM
        run: 
          sudo chmod +x ./gradlew
          ./gradlew build sonar --info -Dsonar.login=$SONAR_TOKEN
